# Generated by Django 4.2.1 on 2023-05-23 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course', models.JSONField(default=list, null=True)),
                ('salary', models.IntegerField(null=True)),
                ('graduation_rate', models.FloatField(default=0.0, null=True)),
                ('cost_0_to_30k', models.IntegerField(null=True)),
                ('cost_30_to_48k', models.IntegerField(null=True)),
                ('cost_48_to_75k', models.IntegerField(null=True)),
                ('cost_75_to_110k', models.IntegerField(null=True)),
                ('cost_110k_plus', models.IntegerField(null=True)),
                ('student_size', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=255)),
                ('acceptance_rate', models.FloatField(default=0.0, null=True)),
                ('grescore', models.FloatField(default=0.0, null=True)),
                ('tuition', models.FloatField(default=0.0, null=True)),
                ('link', models.CharField(default='#', max_length=255)),
                ('toefl', models.IntegerField(null=True)),
                ('ielts', models.IntegerField(null=True)),
                ('cs_salary', models.IntegerField(null=True)),
                ('datascience_salary', models.IntegerField(null=True)),
                ('MBA_salary', models.IntegerField(null=True)),
                ('logo', models.CharField(default='None', max_length=50)),
                ('MBA_cost', models.IntegerField(null=True)),
                ('CSE_cost', models.IntegerField(null=True)),
                ('DataScience_cost', models.IntegerField(null=True)),
                ('country', models.CharField(default='USA', max_length=50)),
                ('hostelandmeals', models.IntegerField(null=True)),
                ('transportation', models.IntegerField(null=True)),
                ('personal', models.IntegerField(null=True)),
                ('gate', models.IntegerField(null=True)),
                ('cat', models.IntegerField(null=True)),
                ('books', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=50)),
                ('amount', models.FloatField(max_length=255)),
                ('deadline', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=250)),
            ],
        ),
    ]
