# Generated by Django 4.2 on 2023-05-22 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_useraccount_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
